// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commander.proto

package twist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateTransactionRequest struct {
	Mode                 string   `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionRequest) Reset()         { *m = CreateTransactionRequest{} }
func (m *CreateTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionRequest) ProtoMessage()    {}
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{0}
}

func (m *CreateTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionRequest.Unmarshal(m, b)
}
func (m *CreateTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionRequest.Marshal(b, m, deterministic)
}
func (m *CreateTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionRequest.Merge(m, src)
}
func (m *CreateTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionRequest.Size(m)
}
func (m *CreateTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionRequest proto.InternalMessageInfo

func (m *CreateTransactionRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type CreateTransactionReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTransactionReply) Reset()         { *m = CreateTransactionReply{} }
func (m *CreateTransactionReply) String() string { return proto.CompactTextString(m) }
func (*CreateTransactionReply) ProtoMessage()    {}
func (*CreateTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{1}
}

func (m *CreateTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTransactionReply.Unmarshal(m, b)
}
func (m *CreateTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTransactionReply.Marshal(b, m, deterministic)
}
func (m *CreateTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTransactionReply.Merge(m, src)
}
func (m *CreateTransactionReply) XXX_Size() int {
	return xxx_messageInfo_CreateTransactionReply.Size(m)
}
func (m *CreateTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTransactionReply proto.InternalMessageInfo

func (m *CreateTransactionReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateTransactionReply) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type ConfirmTransactionRequest struct {
	TransactionID        string               `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Tasks                []*TransactionTask   `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Expires              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=expires,proto3" json:"expires,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ConfirmTransactionRequest) Reset()         { *m = ConfirmTransactionRequest{} }
func (m *ConfirmTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransactionRequest) ProtoMessage()    {}
func (*ConfirmTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{2}
}

func (m *ConfirmTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmTransactionRequest.Unmarshal(m, b)
}
func (m *ConfirmTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmTransactionRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmTransactionRequest.Merge(m, src)
}
func (m *ConfirmTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmTransactionRequest.Size(m)
}
func (m *ConfirmTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmTransactionRequest proto.InternalMessageInfo

func (m *ConfirmTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *ConfirmTransactionRequest) GetTasks() []*TransactionTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *ConfirmTransactionRequest) GetExpires() *timestamp.Timestamp {
	if m != nil {
		return m.Expires
	}
	return nil
}

type ConfirmTransactionReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmTransactionReply) Reset()         { *m = ConfirmTransactionReply{} }
func (m *ConfirmTransactionReply) String() string { return proto.CompactTextString(m) }
func (*ConfirmTransactionReply) ProtoMessage()    {}
func (*ConfirmTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{3}
}

func (m *ConfirmTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmTransactionReply.Unmarshal(m, b)
}
func (m *ConfirmTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmTransactionReply.Marshal(b, m, deterministic)
}
func (m *ConfirmTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmTransactionReply.Merge(m, src)
}
func (m *ConfirmTransactionReply) XXX_Size() int {
	return xxx_messageInfo_ConfirmTransactionReply.Size(m)
}
func (m *ConfirmTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmTransactionReply proto.InternalMessageInfo

func (m *ConfirmTransactionReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ConfirmTransactionReply) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type TransactionTask struct {
	Confirm              *TransactionTaskAction `protobuf:"bytes,1,opt,name=confirm,proto3" json:"confirm,omitempty"`
	Cancel               *TransactionTaskAction `protobuf:"bytes,2,opt,name=cancel,proto3" json:"cancel,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionTask) Reset()         { *m = TransactionTask{} }
func (m *TransactionTask) String() string { return proto.CompactTextString(m) }
func (*TransactionTask) ProtoMessage()    {}
func (*TransactionTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{4}
}

func (m *TransactionTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTask.Unmarshal(m, b)
}
func (m *TransactionTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTask.Marshal(b, m, deterministic)
}
func (m *TransactionTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTask.Merge(m, src)
}
func (m *TransactionTask) XXX_Size() int {
	return xxx_messageInfo_TransactionTask.Size(m)
}
func (m *TransactionTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTask.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTask proto.InternalMessageInfo

func (m *TransactionTask) GetConfirm() *TransactionTaskAction {
	if m != nil {
		return m.Confirm
	}
	return nil
}

func (m *TransactionTask) GetCancel() *TransactionTaskAction {
	if m != nil {
		return m.Cancel
	}
	return nil
}

type TransactionTaskAction struct {
	Type                 string            `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Method               string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Uri                  string            `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Headers              map[string]string `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Payload              string            `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionTaskAction) Reset()         { *m = TransactionTaskAction{} }
func (m *TransactionTaskAction) String() string { return proto.CompactTextString(m) }
func (*TransactionTaskAction) ProtoMessage()    {}
func (*TransactionTaskAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_36bf467611423882, []int{5}
}

func (m *TransactionTaskAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionTaskAction.Unmarshal(m, b)
}
func (m *TransactionTaskAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionTaskAction.Marshal(b, m, deterministic)
}
func (m *TransactionTaskAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionTaskAction.Merge(m, src)
}
func (m *TransactionTaskAction) XXX_Size() int {
	return xxx_messageInfo_TransactionTaskAction.Size(m)
}
func (m *TransactionTaskAction) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionTaskAction.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionTaskAction proto.InternalMessageInfo

func (m *TransactionTaskAction) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TransactionTaskAction) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TransactionTaskAction) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *TransactionTaskAction) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *TransactionTaskAction) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateTransactionRequest)(nil), "twist.CreateTransactionRequest")
	proto.RegisterType((*CreateTransactionReply)(nil), "twist.CreateTransactionReply")
	proto.RegisterType((*ConfirmTransactionRequest)(nil), "twist.ConfirmTransactionRequest")
	proto.RegisterType((*ConfirmTransactionReply)(nil), "twist.ConfirmTransactionReply")
	proto.RegisterType((*TransactionTask)(nil), "twist.TransactionTask")
	proto.RegisterType((*TransactionTaskAction)(nil), "twist.TransactionTaskAction")
	proto.RegisterMapType((map[string]string)(nil), "twist.TransactionTaskAction.HeadersEntry")
}

func init() { proto.RegisterFile("commander.proto", fileDescriptor_36bf467611423882) }

var fileDescriptor_36bf467611423882 = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x71, 0xd2, 0x24, 0x64, 0x02, 0x2a, 0x8c, 0x20, 0x2c, 0x16, 0xd0, 0xc8, 0xe2, 0x10,
	0x24, 0xb4, 0x95, 0x42, 0x85, 0x50, 0x6f, 0x28, 0x20, 0xc1, 0xd5, 0x32, 0x52, 0x39, 0x6e, 0xed,
	0x69, 0x6b, 0xc5, 0xf6, 0x9a, 0xdd, 0x35, 0xe0, 0x13, 0x4f, 0xc3, 0x5b, 0xf0, 0x50, 0x3c, 0x02,
	0xf2, 0xda, 0x0b, 0x85, 0x38, 0xe5, 0xd2, 0xdb, 0x8c, 0xf5, 0xcd, 0xbf, 0xff, 0xfe, 0x9e, 0x85,
	0xfd, 0x58, 0xe6, 0xb9, 0x28, 0x12, 0x52, 0xbc, 0x54, 0xd2, 0x48, 0x1c, 0x99, 0x2f, 0xa9, 0x36,
	0xfe, 0xc1, 0xb9, 0x94, 0xe7, 0x19, 0x1d, 0xda, 0x8f, 0xa7, 0xd5, 0xd9, 0xa1, 0x49, 0x73, 0xd2,
	0x46, 0xe4, 0x65, 0xcb, 0x05, 0x1c, 0xd8, 0x5a, 0x91, 0x30, 0x14, 0x29, 0x51, 0x68, 0x11, 0x9b,
	0x54, 0x16, 0x21, 0x7d, 0xaa, 0x48, 0x1b, 0x44, 0xd8, 0xcb, 0x65, 0x42, 0xcc, 0x5b, 0x78, 0xcb,
	0x69, 0x68, 0xeb, 0xe0, 0x04, 0xe6, 0x3d, 0x7c, 0x99, 0xd5, 0xc8, 0x60, 0xa2, 0xab, 0x38, 0x26,
	0xad, 0xed, 0xc0, 0xcd, 0xd0, 0xb5, 0xf8, 0x14, 0x6e, 0x9b, 0x3f, 0xf4, 0xfb, 0x37, 0x6c, 0x60,
	0x05, 0xff, 0xfe, 0x18, 0x7c, 0xf7, 0xe0, 0xe1, 0x5a, 0x16, 0x67, 0xa9, 0xca, 0x7b, 0xbc, 0x6c,
	0x69, 0x78, 0x3d, 0x1a, 0xf8, 0x1c, 0x46, 0x46, 0xe8, 0x8d, 0x66, 0x83, 0xc5, 0x70, 0x39, 0x5b,
	0xcd, 0xb9, 0x4d, 0x81, 0x5f, 0xd2, 0x8b, 0x84, 0xde, 0x84, 0x2d, 0x84, 0x47, 0x30, 0xa1, 0xaf,
	0x65, 0xaa, 0x48, 0xb3, 0xe1, 0xc2, 0x5b, 0xce, 0x56, 0x3e, 0x6f, 0xe3, 0xe2, 0x2e, 0x2e, 0x1e,
	0xb9, 0xb8, 0x42, 0x87, 0x06, 0x1f, 0xe1, 0x41, 0x9f, 0xcd, 0xeb, 0x88, 0xe0, 0x1b, 0xec, 0xff,
	0x63, 0x15, 0x5f, 0xc2, 0x24, 0x6e, 0x4f, 0xb3, 0x92, 0xb3, 0xd5, 0xa3, 0xfe, 0x3b, 0xbd, 0x6e,
	0x6d, 0x38, 0x18, 0x8f, 0x60, 0x1c, 0x8b, 0x22, 0xa6, 0xcc, 0x9e, 0xf4, 0xbf, 0xb1, 0x8e, 0x0d,
	0x7e, 0x7a, 0x70, 0xbf, 0x97, 0x68, 0x76, 0x21, 0xaa, 0xcb, 0xdf, 0xbb, 0xd0, 0xd4, 0x38, 0x87,
	0x71, 0x4e, 0xe6, 0x42, 0x26, 0xdd, 0x6d, 0xba, 0x0e, 0xef, 0xc0, 0xb0, 0x52, 0xa9, 0xcd, 0x74,
	0x1a, 0x36, 0x25, 0xae, 0x61, 0x72, 0x41, 0x22, 0x21, 0xa5, 0xd9, 0x9e, 0xfd, 0x33, 0xcf, 0xae,
	0xb2, 0xc3, 0xdf, 0xb5, 0xec, 0xdb, 0xc2, 0xa8, 0x3a, 0x74, 0x93, 0x4d, 0xba, 0xa5, 0xa8, 0x33,
	0x29, 0x12, 0x36, 0xb2, 0xd2, 0xae, 0xf5, 0x8f, 0xe1, 0xd6, 0xe5, 0x91, 0xc6, 0xc0, 0x86, 0xea,
	0xce, 0x6b, 0x53, 0xe2, 0x3d, 0x18, 0x7d, 0x16, 0x59, 0x45, 0x9d, 0xd3, 0xb6, 0x39, 0x1e, 0xbc,
	0xf2, 0x56, 0x3f, 0x3c, 0x98, 0xae, 0xdd, 0xe3, 0xc1, 0x0f, 0x70, 0x77, 0x6b, 0xbd, 0xf1, 0xa0,
	0x33, 0xbb, 0xeb, 0xa1, 0xf8, 0x8f, 0x77, 0x03, 0x65, 0x56, 0x07, 0x37, 0xf0, 0x04, 0x70, 0x7b,
	0x67, 0x70, 0xe1, 0xc6, 0x76, 0x6d, 0xbd, 0xff, 0xe4, 0x0a, 0xc2, 0x2a, 0x9f, 0x8e, 0xed, 0xaa,
	0xbe, 0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x83, 0x60, 0x69, 0x46, 0x01, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommanderClient is the client API for Commander service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommanderClient interface {
	CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionReply, error)
	ConfirmTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionReply, error)
}

type commanderClient struct {
	cc *grpc.ClientConn
}

func NewCommanderClient(cc *grpc.ClientConn) CommanderClient {
	return &commanderClient{cc}
}

func (c *commanderClient) CreateTransaction(ctx context.Context, in *CreateTransactionRequest, opts ...grpc.CallOption) (*CreateTransactionReply, error) {
	out := new(CreateTransactionReply)
	err := c.cc.Invoke(ctx, "/twist.Commander/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commanderClient) ConfirmTransaction(ctx context.Context, in *ConfirmTransactionRequest, opts ...grpc.CallOption) (*ConfirmTransactionReply, error) {
	out := new(ConfirmTransactionReply)
	err := c.cc.Invoke(ctx, "/twist.Commander/ConfirmTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommanderServer is the server API for Commander service.
type CommanderServer interface {
	CreateTransaction(context.Context, *CreateTransactionRequest) (*CreateTransactionReply, error)
	ConfirmTransaction(context.Context, *ConfirmTransactionRequest) (*ConfirmTransactionReply, error)
}

// UnimplementedCommanderServer can be embedded to have forward compatible implementations.
type UnimplementedCommanderServer struct {
}

func (*UnimplementedCommanderServer) CreateTransaction(ctx context.Context, req *CreateTransactionRequest) (*CreateTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (*UnimplementedCommanderServer) ConfirmTransaction(ctx context.Context, req *ConfirmTransactionRequest) (*ConfirmTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmTransaction not implemented")
}

func RegisterCommanderServer(s *grpc.Server, srv CommanderServer) {
	s.RegisterService(&_Commander_serviceDesc, srv)
}

func _Commander_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twist.Commander/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).CreateTransaction(ctx, req.(*CreateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commander_ConfirmTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommanderServer).ConfirmTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twist.Commander/ConfirmTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommanderServer).ConfirmTransaction(ctx, req.(*ConfirmTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commander_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twist.Commander",
	HandlerType: (*CommanderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _Commander_CreateTransaction_Handler,
		},
		{
			MethodName: "ConfirmTransaction",
			Handler:    _Commander_ConfirmTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "commander.proto",
}
