// Code generated by protoc-gen-go. DO NOT EDIT.
// source: supervisor.proto

package twist

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransactionRequest struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{0}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *TransactionRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type TransactionEvent struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	RunnerID             string   `protobuf:"bytes,2,opt,name=RunnerID,proto3" json:"RunnerID,omitempty"`
	EventName            string   `protobuf:"bytes,3,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Payload              string   `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{1}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *TransactionEvent) GetRunnerID() string {
	if m != nil {
		return m.RunnerID
	}
	return ""
}

func (m *TransactionEvent) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *TransactionEvent) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type PrepareTransactionRequest struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Mode                 string   `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareTransactionRequest) Reset()         { *m = PrepareTransactionRequest{} }
func (m *PrepareTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareTransactionRequest) ProtoMessage()    {}
func (*PrepareTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{2}
}

func (m *PrepareTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareTransactionRequest.Unmarshal(m, b)
}
func (m *PrepareTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareTransactionRequest.Marshal(b, m, deterministic)
}
func (m *PrepareTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareTransactionRequest.Merge(m, src)
}
func (m *PrepareTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareTransactionRequest.Size(m)
}
func (m *PrepareTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareTransactionRequest proto.InternalMessageInfo

func (m *PrepareTransactionRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *PrepareTransactionRequest) GetMode() string {
	if m != nil {
		return m.Mode
	}
	return ""
}

type PrepareTransactionReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TransactionID        string   `protobuf:"bytes,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareTransactionReply) Reset()         { *m = PrepareTransactionReply{} }
func (m *PrepareTransactionReply) String() string { return proto.CompactTextString(m) }
func (*PrepareTransactionReply) ProtoMessage()    {}
func (*PrepareTransactionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{3}
}

func (m *PrepareTransactionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareTransactionReply.Unmarshal(m, b)
}
func (m *PrepareTransactionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareTransactionReply.Marshal(b, m, deterministic)
}
func (m *PrepareTransactionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareTransactionReply.Merge(m, src)
}
func (m *PrepareTransactionReply) XXX_Size() int {
	return xxx_messageInfo_PrepareTransactionReply.Size(m)
}
func (m *PrepareTransactionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareTransactionReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareTransactionReply proto.InternalMessageInfo

func (m *PrepareTransactionReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PrepareTransactionReply) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

type UpdateAssignmentRequest struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	RunnerID             string   `protobuf:"bytes,2,opt,name=runnerID,proto3" json:"runnerID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAssignmentRequest) Reset()         { *m = UpdateAssignmentRequest{} }
func (m *UpdateAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAssignmentRequest) ProtoMessage()    {}
func (*UpdateAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{4}
}

func (m *UpdateAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAssignmentRequest.Unmarshal(m, b)
}
func (m *UpdateAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAssignmentRequest.Merge(m, src)
}
func (m *UpdateAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAssignmentRequest.Size(m)
}
func (m *UpdateAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAssignmentRequest proto.InternalMessageInfo

func (m *UpdateAssignmentRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *UpdateAssignmentRequest) GetRunnerID() string {
	if m != nil {
		return m.RunnerID
	}
	return ""
}

type UpdateAssignmentReply struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAssignmentReply) Reset()         { *m = UpdateAssignmentReply{} }
func (m *UpdateAssignmentReply) String() string { return proto.CompactTextString(m) }
func (*UpdateAssignmentReply) ProtoMessage()    {}
func (*UpdateAssignmentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8b9452d77b1c7d2, []int{5}
}

func (m *UpdateAssignmentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAssignmentReply.Unmarshal(m, b)
}
func (m *UpdateAssignmentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAssignmentReply.Marshal(b, m, deterministic)
}
func (m *UpdateAssignmentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAssignmentReply.Merge(m, src)
}
func (m *UpdateAssignmentReply) XXX_Size() int {
	return xxx_messageInfo_UpdateAssignmentReply.Size(m)
}
func (m *UpdateAssignmentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAssignmentReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAssignmentReply proto.InternalMessageInfo

func (m *UpdateAssignmentReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*TransactionRequest)(nil), "twist.TransactionRequest")
	proto.RegisterType((*TransactionEvent)(nil), "twist.TransactionEvent")
	proto.RegisterType((*PrepareTransactionRequest)(nil), "twist.PrepareTransactionRequest")
	proto.RegisterType((*PrepareTransactionReply)(nil), "twist.PrepareTransactionReply")
	proto.RegisterType((*UpdateAssignmentRequest)(nil), "twist.UpdateAssignmentRequest")
	proto.RegisterType((*UpdateAssignmentReply)(nil), "twist.UpdateAssignmentReply")
}

func init() { proto.RegisterFile("supervisor.proto", fileDescriptor_b8b9452d77b1c7d2) }

var fileDescriptor_b8b9452d77b1c7d2 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xff, 0xe9, 0xbf, 0x6a, 0x3a, 0x20, 0x84, 0x01, 0x69, 0x0c, 0x45, 0xca, 0xe2, 0xc1,
	0x53, 0x40, 0x7d, 0x02, 0xa1, 0x1e, 0x7a, 0x29, 0x12, 0x2d, 0x28, 0x9e, 0xd6, 0x64, 0x90, 0x40,
	0xb2, 0xbb, 0xee, 0x6e, 0x2a, 0x79, 0x07, 0x9f, 0xc8, 0xa7, 0x93, 0x2e, 0xa6, 0xd5, 0xa6, 0x29,
	0x0a, 0xde, 0xf2, 0xcd, 0x97, 0xfd, 0xcd, 0x37, 0xc3, 0x40, 0x60, 0x2a, 0x45, 0x7a, 0x91, 0x1b,
	0xa9, 0x63, 0xa5, 0xa5, 0x95, 0xb8, 0x67, 0x5f, 0x73, 0x63, 0xd9, 0x0c, 0xf0, 0x4e, 0x73, 0x61,
	0x78, 0x6a, 0x73, 0x29, 0x12, 0x7a, 0xa9, 0xc8, 0x58, 0x3c, 0x85, 0x43, 0xbb, 0xae, 0x4e, 0x27,
	0xa1, 0x37, 0xf6, 0xce, 0x06, 0xc9, 0xf7, 0x22, 0x22, 0xf4, 0x4b, 0x99, 0x51, 0xd8, 0x73, 0xa6,
	0xfb, 0x66, 0x6f, 0x1e, 0x04, 0x5f, 0x80, 0xd7, 0x0b, 0x12, 0x3f, 0xc5, 0x45, 0xe0, 0x27, 0x95,
	0x10, 0xa4, 0xa7, 0x93, 0x4f, 0xe4, 0x4a, 0xe3, 0x08, 0x06, 0xb4, 0x44, 0xcd, 0x78, 0x49, 0xe1,
	0x7f, 0x67, 0xae, 0x0b, 0x18, 0xc2, 0x81, 0xe2, 0x75, 0x21, 0x79, 0x16, 0xf6, 0x9d, 0xd7, 0x48,
	0x36, 0x87, 0xe3, 0x1b, 0x4d, 0x8a, 0x6b, 0xfa, 0xd3, 0x29, 0x1f, 0x60, 0xb8, 0x0d, 0xab, 0x8a,
	0x7a, 0x99, 0xc5, 0x54, 0x69, 0x4a, 0xc6, 0x38, 0x9c, 0x9f, 0x34, 0xb2, 0xdd, 0xae, 0xb7, 0xa5,
	0x1d, 0x7b, 0x84, 0xe1, 0x5c, 0x65, 0xdc, 0xd2, 0x95, 0x31, 0xf9, 0xb3, 0x28, 0x49, 0xd8, 0xdf,
	0xe5, 0x8d, 0xc0, 0xd7, 0x1b, 0x6b, 0x6c, 0x34, 0x3b, 0x87, 0xa3, 0x36, 0x7c, 0x67, 0xea, 0x8b,
	0x77, 0x0f, 0xe0, 0x76, 0x75, 0x3c, 0x78, 0x0f, 0xd8, 0x9e, 0x1c, 0xc7, 0xb1, 0xbb, 0xa6, 0xb8,
	0x73, 0xd7, 0xd1, 0xc9, 0x8e, 0x3f, 0x54, 0x51, 0xb3, 0x7f, 0x98, 0x40, 0xb0, 0x99, 0x0d, 0x9b,
	0x57, 0x1d, 0x1b, 0x89, 0x46, 0x9d, 0xbe, 0x63, 0x3e, 0xed, 0xbb, 0x5b, 0xbf, 0xfc, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xd6, 0xf0, 0x05, 0xb7, 0xff, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SupervisorClient is the client API for Supervisor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SupervisorClient interface {
	PrepareTransaction(ctx context.Context, in *PrepareTransactionRequest, opts ...grpc.CallOption) (*PrepareTransactionReply, error)
	UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*UpdateAssignmentReply, error)
}

type supervisorClient struct {
	cc *grpc.ClientConn
}

func NewSupervisorClient(cc *grpc.ClientConn) SupervisorClient {
	return &supervisorClient{cc}
}

func (c *supervisorClient) PrepareTransaction(ctx context.Context, in *PrepareTransactionRequest, opts ...grpc.CallOption) (*PrepareTransactionReply, error) {
	out := new(PrepareTransactionReply)
	err := c.cc.Invoke(ctx, "/twist.Supervisor/PrepareTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorClient) UpdateAssignment(ctx context.Context, in *UpdateAssignmentRequest, opts ...grpc.CallOption) (*UpdateAssignmentReply, error) {
	out := new(UpdateAssignmentReply)
	err := c.cc.Invoke(ctx, "/twist.Supervisor/UpdateAssignment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServer is the server API for Supervisor service.
type SupervisorServer interface {
	PrepareTransaction(context.Context, *PrepareTransactionRequest) (*PrepareTransactionReply, error)
	UpdateAssignment(context.Context, *UpdateAssignmentRequest) (*UpdateAssignmentReply, error)
}

// UnimplementedSupervisorServer can be embedded to have forward compatible implementations.
type UnimplementedSupervisorServer struct {
}

func (*UnimplementedSupervisorServer) PrepareTransaction(ctx context.Context, req *PrepareTransactionRequest) (*PrepareTransactionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareTransaction not implemented")
}
func (*UnimplementedSupervisorServer) UpdateAssignment(ctx context.Context, req *UpdateAssignmentRequest) (*UpdateAssignmentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAssignment not implemented")
}

func RegisterSupervisorServer(s *grpc.Server, srv SupervisorServer) {
	s.RegisterService(&_Supervisor_serviceDesc, srv)
}

func _Supervisor_PrepareTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).PrepareTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twist.Supervisor/PrepareTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).PrepareTransaction(ctx, req.(*PrepareTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Supervisor_UpdateAssignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssignmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServer).UpdateAssignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twist.Supervisor/UpdateAssignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServer).UpdateAssignment(ctx, req.(*UpdateAssignmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Supervisor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twist.Supervisor",
	HandlerType: (*SupervisorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PrepareTransaction",
			Handler:    _Supervisor_PrepareTransaction_Handler,
		},
		{
			MethodName: "UpdateAssignment",
			Handler:    _Supervisor_UpdateAssignment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supervisor.proto",
}
